name: Release
on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          AUTHOR=$(git show ${{ github.ref_name }} --format=reference | grep Tagger | head -n1)
          DATE=$(git show ${{ github.ref_name }} | grep Date)
          echo "author=${AUTHOR}" >> $GITHUB_ENV
          echo "date=${DATE}" >> $GITHUB_ENV
          echo "title=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.title }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Create issue
        if: always()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: ${{ env.title }}
          labels: RELEASE
          body: |
            ### Основная информация
            - ${{ env.author }}
            - ${{ env.date }}
            ### Changelog
            ${{ steps.changelog.outputs.changelog }}
