name: Test
on: [pull_request, workflow_call]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run unit-tests
        run: npm run test
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run e2e-tests
        run: npm run e2e