name: shri-infrustructure
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run unit-tests
        run: npm run test
      - name: Run e2e-tests
        run: npm run e2e